@BASE_URL = http://localhost:3001/api/

GET {{BASE_URL}}menu/

###

DELETE {{BASE_URL}}delete-food/11

###

POST {{BASE_URL}}login/ 
Content-Type: application/json

{ "username": "admin", "password": "password" }


###

POST {{BASE_URL}}signup/ 
Content-Type: application/json

{ "username": "admin2", "password": "password" }


###

GET {{BASE_URL}}orders/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2ODI0NzI0Mzh9.tip6308Eje0_qy2JEJLRHqoyjWFsUhPMOMsGdclh1Wo